[accessibility]
ui_scale = 1.2

[bar]
order = [ "default", "bottom" ]

    [bar.bottom]
    background_opacity = 0.59999998658895493
    capsule = true
    capsule_opacity = 0.89999997988343239
    capsule_padding = 10.0
    center = [ "group:g1" ]
    enabled = true
    end = [ "group:g2", "clock" ]
    position = "bottom"
    start = [ "control-center", "wallpaper", "group:g3", "group:g4" ]

        [[bar.bottom.capsule_group]]
        accordion = false
        accordion_direction = "end"
        enabled = true
        fill = "surface_variant"
        id = "g1"
        members = [ "launcher", "taskbar" ]
        opacity = 0.89999997615814209
        padding = 10.0

        [[bar.bottom.capsule_group]]
        accordion = false
        accordion_direction = "end"
        enabled = true
        fill = "surface_variant"
        id = "g2"
        members = [ "tray", "notifications", "clipboard", "network", "bluetooth", "volume", "brightness" ]
        opacity = 0.89999997615814209
        padding = 10.0

        [[bar.bottom.capsule_group]]
        accordion = false
        accordion_direction = "end"
        enabled = true
        fill = "surface_variant"
        id = "g3"
        members = [ "Neverwinter", "Background" ]
        opacity = 0.89999997615814209
        padding = 10.0

        [[bar.bottom.capsule_group]]
        accordion = false
        accordion_direction = "end"
        enabled = true
        fill = "surface_variant"
        id = "g4"
        members = [ "Antigravity", "RustDesk" ]
        opacity = 0.89999997615814209
        padding = 10.0

    [bar.default]
    background_opacity = 0.59999998658895493
    capsule = true
    center = [ "workspaces", "active_window", "spacer_1" ]
    concave_edge_corners = true
    end = [ "screenshot", "media", "spacer_1", "date" ]
    margin_edge = 0
    margin_ends = 0
    opacity = 0.65000000000000002
    radius = 76
    radius_bottom_left = 12
    radius_bottom_right = 12
    radius_top_left = 0
    radius_top_right = 0
    scale = 1.1000000000000001
    start = [ "session", "launcher", "spacer_1", "group:g1" ]
    thickness = 35

        [[bar.default.capsule_group]]
        accordion = false
        accordion_direction = "end"
        border = ""
        enabled = true
        fill = "on_secondary"
        id = "g1"
        members = [ "temp", "sysmon_2", "sysmon_3", "ram", "cpu" ]
        opacity = 0.75
        padding = 6.0

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@DP-3", "lockscreen-login-box@HDMI-A-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-3"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "DP-3"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-3".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "HDMI-A-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[shell]
clipboard_image_action_command = "swash --stdin --name \"swash-$(date +'%Y-%m-%d_%H:%M:%S').png\""
launch_apps_as_systemd_services = true
polkit_agent = true
settings_show_advanced = true

    [shell.animations]
    duration_ms = 200
    enabled = true

    [shell.greeter_sync]
    auto_sync = false

    [shell.panel]
    open_near_click_control_center = true
    session_placement = "floating"
    session_position = "center"
    transparency_mode = "glass"

    [shell.screenshot]
    copy_to_clipboard = false
    pipe_command = "swash --stdin --name \"swash-$(date +'%Y-%m-%d_%H:%M:%S').png\""
    pipe_to_command = true
    save_to_file = false

    [[shell.session.actions]]
    action = "lock"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "1"
    variant = "default"

    [[shell.session.actions]]
    action = "logout"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "2"
    variant = "default"

    [[shell.session.actions]]
    action = "lock_and_suspend"
    countdown_seconds = 3.0
    enabled = true
    shortcut = "3"
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    countdown_seconds = 3.0
    enabled = true
    shortcut = "4"
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    countdown_seconds = 3.0
    enabled = true
    shortcut = "5"
    variant = "destructive"

    [shell.shadow]
    alpha = 0.3899999912828207

[system.monitor]
gpu_poll_seconds = 2

[theme]
builtin = "Dracula"
community_palette = "Oxocarbon"
mode = "dark"
shell_mode = "dark"
source = "builtin"
surface_opacity = 0.59999999999999998
wallpaper_scheme = "m3-content"

    [theme.blur]
    enabled = true
    opacity = 0.65000000000000002
    radius = 16

    [theme.templates]
    builtin_ids = [ "btop", "gtk3", "gtk4", "kcolorscheme", "kitty", "qt", "alacritty" ]

[wallpaper.default]
path = "/mnt/ddrive/Pictures/wallpapers/yuru-camp-0.png"

[wallpaper.last]
path = "/mnt/ddrive/Pictures/wallpapers/yuru-camp-0.png"

[wallpaper.monitors.DP-3]
path = "/mnt/ddrive/Pictures/wallpapers/yuru-camp-0.png"

[wallpaper.monitors.HDMI-A-1]
path = "/mnt/ddrive/Pictures/wallpapers/yuru-camp-0.png"

[widget.Antigravity]
custom_image = "/opt/Antigravity_IDE/resources/app/resources/linux/code.png"
type = "custom_button"

    [widget.Antigravity.actions]
    left = "exec /opt/Antigravity_IDE/antigravity-ide"

[widget.Background]
glyph = "image"
type = "custom_button"

    [widget.Background.actions]
    left = "exec pkill mpvpaper; mpvpaper -n 300 -o \"no-audio --loop-playlist --shuffle\" ALL /mnt/ddrive/Pictures/wallpapers/animated/anime & disown"
    right = "exec pkill mpvpaper"

[widget.Neverwinter]
custom_image = "/mnt/ddrive/SteamLibrary/steamapps/common/Cryptic Studios/logo.png"
type = "custom_button"

    [widget.Neverwinter.actions]
    left = "exec /mnt/ddrive/home/apps/Neverwinter.sh"

[widget.RustDesk]
custom_image = "/var/lib/flatpak/app/com.rustdesk.RustDesk/x86_64/stable/active/export/share/icons/hicolor/256x256/apps/com.rustdesk.RustDesk.png"
type = "custom_button"

    [widget.RustDesk.actions]
    left = "exec flatpak run com.rustdesk.RustDesk"

[widget.active_window]
display = "icon_only"
icon_size = 24
min_length = 0

[widget.clock]
anchor = true
color = "primary"
font_weight = 700
format = "{:%H:%M:%S}"

[widget.control-center]
enabled = false

[widget.cpu.actions]
right = "exec gnome-system-monitor"

[widget.date]
color = "primary"
font_weight = 700
format = "{:%d/%m/%Y}"

[widget.launcher]
color = "secondary"

[widget.media]
hide_when_no_media = true
title_scroll = "on_hover"

[widget.network]
color = "secondary"
show_label = false

[widget.notifications]
color = "secondary"

[widget.ram.actions]
right = "exec gnome-system-monitor"

[widget.session]
color = "error"

[widget.spacer_1]
enabled = false
type = "spacer"

[widget.sysmon_2]
enabled = false
glyph = "gpu-usage"
show_value = false
stat = "gpu_temp"
type = "sysmon"

[widget.sysmon_3]
enabled = false
glyph = "cpu-2"
stat = "ram_used"
type = "sysmon"

[widget.temp]
enabled = false
show_value = false

[widget.tray]
capsule = true
capsule_fill = "on_secondary"

[widget.volume]
color = "secondary"

[widget.wallpaper]
enabled = false

[widget.workspaces]
active_pill_size = 2.5
capsule = true
capsule_fill = "on_primary"
color = "tertiary"
focused_color = "tertiary"
font_weight = 700
inactive_pill_size = 1.0
label_source = "name"
pill_scale = 0.80000000000000004
show_labels = true
